### PR TITLE
feat: make download of assets possible

### PR DESCRIPTION
**Pull request by ahuemmer**
This time, something larger from me... 😉 I'd like to have the ability to download assets by their asset id. To do so, it is necessary to change the `Accept` header in the corresponding GET request and also follow redirects using the `-L` flag in curl.

Please check whether the way I implemented both comes up to your expectations. :) 
I tried to make the `Accept` header customizable, yet respecting the default `${OK_SH_ACCEPT}`. The parameter must then be routed through `_get` to `_request`.
The `-L` curl flag is hard coded as IMHO it will have no impact on the rest of the functionality (at least, it didn't during my tests 😊).

### CODE REVIEW

**Comment by whiteinge** [comment]
Ooh, interesting use-case and nice implementation. At first glance I think passing `accept` along is exactly the right way to go.

Unrelated to your changes, I'm seeing a bug in my code perhaps around parsing the HTTP response. It's causing the headers to be output along with the release asset itself. I'd like to track that down and fix it while I can reproduce it and then I'll get this merged.

**Comment by whiteinge** [comment]
Oh, I misread. The `-L` flag is outputting two sets of headers, one for the 302 and one for the 200, and the parsing stops after that first one. :thinking:

**Comment by ahuemmer** [comment]
Oops, sorry, I didn't see that. 😳 I'll have a look into this. IMHO, the best solution would be to parse only the "last" received header. Would you agree? :)

**Comment by ahuemmer** [comment]
I've tried around with this now and here's a working solution in case you like the idea of removing the first header(s):

```sh
_strip_first_headers() {
    # Remove all but the last HTTP headers (retrieved by curl) from the output
    #
    # This is necessary as redirect-following (curl flag `-L`) will cause curl
    # to return _all_ headers encountered. Here, we just need to get the "last"
    # one, as this is the one belongig to the final data retrieved.
    local current_header
    local header_finished=0
    while read -r line; do
        if [[ "$line" =~ ^HTTP/[1-2](\.[0-9])?[[:space:]]+[0-9]{3}[[:space:]].+$ ]]; then
            current_header="${line}"
        elif [ ${header_finished} -eq 1 ]; then
            echo "${current_header}"
            echo "${crlf}"
            echo "${line}"
            break
        else
          current_header="${current_header}${crlf}${line}"
        fi
        if [ "${line}" = "$crlf" ]; then
            header_finished=1
        else
            header_finished=0
        fi
  done

  cat
}
```

You would then just have to pipe the output from `_request` through this function first, before processing them further. For me, this works fine with the things I've tested. :)

**Comment by whiteinge** [comment]
Sorry for the slow response(s)! I've been AFK more than usual this week.

That approach looks fine to me, thanks for slinging more code. I'm also wondering about what it might mean to bake 3xx support directly into the `_response` function. If we get a 3xx response with a Location header I *think* we'd pretty much always want to follow it and that would dovetail with adding the `-L` flag in `_request`. I'll sleep on it to see if I can think of a reason we wouldn't want that. What are your thoughts?

**Comment by ahuemmer** [comment]
No need to apologize, definitely! 😃 Most of us have enough to do already without GitHub PRs. 😉
I had also thought about this option, but - for the moment - disregarded it because of two reasons:

1. When first experimenting with `ok.sh`, I had inadvertently misconfigured my GitHub credentials and was therefore forwarded to to GitHub login page via a 30x response. Following this redirect would possible be the cause of a less traceable behavior / less "senseful" answer in such cases.
2. To be honest, the main reason was, on first sight, it seemed to me to be a lot more of work / things to consider than my rather quick and dirty solution. 😳 

Anyway, IMHO your approach is the "cleaner" way to do it. I'm curious about how this goes on - please let me know if I can help in any way!

**Comment by whiteinge** [comment]
Thanks for the feedback! The trouble you saw with the redirect to the login page is a compelling reason _not_ to do it the way I suggested.

How about we add the `_strip_first_headers` function so we can call it on an as-needed basis like you suggested, and we also make the `-L` flag conditional with a new `follow_redirects` param in `_request`? That way both the request and parsing the response are explicit opt-ins when it comes to handling redirects.

**Comment by ahuemmer** [comment]
Yes, that sounds like the best solution to me! 😃 We would then have the new feature and flexibility and still make sure we don't mess anything up concerning the rest of the functionality.

**Comment by whiteinge** [comment]
It (eventually) occurred to me that downloading assets is better be handled outside of this script. GitHub can give us the browser download URL(s) and once we have that it's a straightforward xargs and curl operation. E.g.:

```
ok.sh release_assets <user> <repo> <release_id> _filter='.[] | .browser_download_url' \
    | xargs -L1 curl -L -O
```

One of the goals of this script is to make the GitHub API interoperate with shell tools and we don't have nearly enough examples of doing so in the docs. It's not trivial to know the GH API, and curl, and xargs, and awk, and...etc, so more examples would help illuminate what's possible. See #90.

I really appreciate that you dove in and slung code and worked with me on the API. Thank you for doing that.

**Pull request closed without merging**
